---
- name: test chocolatey with ansible
  hosts: all
  tasks:
    - name: Install Firefox
      win_chocolatey:
        name: firefox
        state: present
    - name: Uninstall Firefox
      win_chocolatey:
        name: firefox
        state: absent
