---
- name: test chocolatey with ansible
  hosts: all
  tasks:
    - name: Install Firefox
      win_chocolatey:
        name: firefox
        state: present
    - name: Install Chrome
      win_chocolatey:
        name: googlechrome
        state: present
    - name: remove all pins for Notepad++ on all versions
      win_chocolatey:
        name: notepadplusplus
        pinned: no
        state: present
      become: yes
      become_user: Administrator
      become_method: runas
