---
- name: test chocolatey with ansible
  hosts: all
  tasks:
    - name: Uninstall Firefox
      win_chocolatey:
        name: firefox
        state: absent
    - name: Uninstall Chrome
      win_chocolatey:
        name: googlechrome
        state: absent
    - name: Uninstall Notepad++
      win_chocolatey:
        name: notepadplusplus
        state: absent
